<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Demand extends Model
{
    use HasFactory;

    protected $fillable = ['fecha',
                            'city_id',
                            'ncliente',
                            'nCredito',
                            'team_id',
                            'promoter_id',
                            'pNombre',
                            'sNombre',
                            'aPaterno',
                            'aMaterno',
                            'genero',
                            'fNacimiento',
                            'lNacimiento',
                            'pais',
                            'nacionalidad',
                            'tidentificaion',
                            'rfc',
                            'curp',
                            'nIdentificacion',
                            'ecivil',
                            'regimen',
                            'nescolar',
                            'oficio',
                            'dudcalle',
                            'dudne',
                            'dudni',
                            'dudcolonia',
                            'dudelegacion',
                            'dudciudad',
                            'dudcp',
                            'dudreferencia',
                            'dudusotelefono',
                            'dudtelefono',
                            'dudrecidencia',
                            'dfnombre',
                            'dftrtabaja',
                            'dfcocupacion',
                            'dfchijos',
                            'dfcdeconomicos',
                            'dseactividad',
                            'dseofinggresos',
                            'dseihogar',
                            'dsenphabitan',
                            'dseccvivienda',
                            'desmaterial',
                            'rfNombre',
                            'rfParentesco',
                            'rfTelefono',
                            'rfDomicilio',
                            'rfcp',
                            'rfOcupacion',
                            'rfLTrabajo',
                            'rpNombre',
                            'rpParentesco',
                            'rpTelefono',
                            'rpDomicilio',
                            'rpcp',
                            'rpOcupacion',
                            'rpLTrabajo',
                            'nempresa',
                            'fechaini',
                            'fechafin',
                            'total',
                            'nempresa2',
                            'fechaini2',
                            'fechafin2',
                            'total2',
                            'tfdirectivos',
                            'dNombre',
                            'ocupuesto',
                            'dNombre2',
                            'Observaciones',
                            'activo'];
}
